CREATE DATABASE PROJECT_DB;

USE PROJECT_DB;

SHOW TABLES;

CREATE TABLE USERS (
    EMAIL VARCHAR(50) UNIQUE,
    PASSWORD VARCHAR(20) NOT NULL ,
    ROLE ENUM('ADMIN','STUDENT') 
);

DESC USERS;

INSERT INTO USERS VALUES('shravanidake17@gmail.com','SHRAU@1726','ADMIN');
INSERT INTO USERS VALUES('zoretrupti08@gmail.com','ZORE8114','STUDENT');
INSERT INTO USERS VALUES('aryapatil2075@gmail.com','ARYA75','ADMIN');
INSERT INTO USERS VALUES('tasalimajamadar205@gmail.com','JAMADAR205','STUDENT');
INSERT INTO USERS VALUES('patilneha0518@gmail.com','NEHA0518','STUDENT');
INSERT INTO users VALUES('s1', 'pass123', 'STUDENT');
INSERT INTO users VALUES('s2', 'pass123', 'STUDENT');
INSERT INTO users VALUES('s3', 'pass123', 'STUDENT');
INSERT INTO users VALUES('admin@test.com', 'admin123', 'ADMIN');
INSERT INTO users VALUES('john@test.com', 'pass123', 'STUDENT');

SELECT * FROM USERS ;

