USE PROJECT_DB;

CREATE TABLE VIDEOS(
    VIDEO_ID INT PRIMARY KEY AUTO_INCREMENT ,
    COURSE_ID INT,
    TITLE VARCHAR(50) NOT NULL,
    DESCP VARCHAR(1000),
    YOUTUBE_URL VARCHAR(200) NOT NULL,
    ADDED_AT DATE,
    CONSTRAINT FK_V_CID FOREIGN KEY (COURSE_ID) REFERENCES COURSES(COURSE_ID)
)AUTO_INCREMENT=1001;

INSERT INTO VIDEOS (COURSE_ID,TITLE,DESCP,YOUTUBE_URL,ADDED_AT) VALUES(101,'MERN','FULL STACK DEVELOPMENT','https://www.youtube.com/watch?v=F9gB5b4jgOI&pp=ygUFTUVSTiDSBwkJKQoBhyohjO8%3D','2025-12-12');
INSERT INTO VIDEOS (COURSE_ID,TITLE,DESCP,YOUTUBE_URL,ADDED_AT) VALUES(102,'PYTHON','BAKEND DEVELOPMENT','https://www.youtube.com/watch?v=RT6IHsuriMI&list=PLryYKs02mpdIMPfxxN29PjIFktQMuiHUm','2025-12-13');
INSERT INTO VIDEOS (COURSE_ID,TITLE,DESCP,YOUTUBE_URL,ADDED_AT) VALUES(103,'GEN-AI','AUTOMATION AND ML','https://www.youtube.com/watch?v=d4yCWBGFCEs&pp=ygUGR0VOLUFJ','2025-12-14');
INSERT INTO VIDEOS (COURSE_ID,TITLE,DESCP,YOUTUBE_URL,ADDED_AT) VALUES(104,'JAVA','PROGRAMMING WITH JAVA','https://www.youtube.com/watch?v=BGTx91t8q50&pp=ygUESkFWQQ%3D%3D','2025-12-15');
INSERT INTO VIDEOS (COURSE_ID,TITLE,DESCP,YOUTUBE_URL,ADDED_AT) VALUES(105,'ANALYTICS','DATA ANALYSIS FOR FORECASTING','https://www.youtube.com/watch?v=2fkRMGIMbXg&pp=ygUNREFUQSBBTkFMWVNJUw%3D%3D','2025-12-16');
INSERT INTO videos(course_id,title,youtube_url,added_at) VALUES(101,'MERN video 6','https://www.youtube.com/watch?v=cCnonxT-oZc','2025-11-26');
INSERT INTO videos(course_id,title,youtube_url,added_at) VALUES(101,'MERN 10','https://www.youtube.com/watch?v=VBhy3ircd_M','2025-11-26');
INSERT INTO videos(course_id,title,youtube_url,added_at) VALUES(103,'Intro to AI','https://www.youtube.com/watch?v=D1eL1EnxXXQ','2025-12-25');
INSERT INTO videos(course_id,title,youtube_url,added_at) VALUES(102,'Python Basics','https://www.youtube.com/watch?v=vLqTf2b6GZw','2025-12-25');


SELECT * FROM VIDEOS;
